### ISSUE TITLE
Datepicker locale

### ISSUE THREAD

**Issue by DanielCambray** [themesberg/flowbite#32]
Hi,

I have installed the datepicker from then CDN and it works just fine. I can change the format with `datepicker-format="dd/mm/yyyy"`. I try now to change the locale with `datepicker-locale="fr-FR"` and/or  `datepicker-language="fr"`. But the locale is still "en". Did I miss something ?

Thanks.

**Comment by zoltanszogyenyi** [comment]
Hey @DanielCambray,

We'll address this issue in the v1.2.1 update.

**Comment by bjorntj** [comment]
Has this been resolved in 1.3.0?

**Comment by MichalPniak** [comment]
Has it been done? Because in version 1.4.1 it is still not possible to change the language.

**Comment by erenergul** [comment]
> Hi, I am impressed with the design and I am considering purchasing a pro version, but I have a question regarding the code content. Does the pro version include exactly the same files as are free? Because I wanted to use your calendar component in my project today and... it didn't work very well.
> 
> I noticed the visual messes that were reported on other issues a while ago, as well as those wretched translations that can't be set.
> 
> From what I can see, the whole problem lies in the file `base-locales.js`, which is only English. My client is from Poland, so I needed a translation that is added but not used.
> 
> ```js
> import {locales} from './i18n/base-locales.js';
> ```

Did you find any solution to translate ? I couldn't translate it.

**Comment by MichalPniak** [comment]
> 

I have not found any solution, I just remember that you would have to overwrite the file where the languages are imported for this plugin. When I analyzed it some time ago, only the English language was being import.

**Comment by MichalPniak** [comment]
I have not found any solution, I just remember that you would have to overwrite the file where the languages are imported for this plugin. When I analyzed it some time ago, only the English language was being import.

**Comment by switch-coders** [comment]
Hi!, this feature will be released in short term? I'm also using the CDN and I want to change the language with Spanish

**Comment by cotufaloschiflones** [comment]
Hi, I'm having the same problem too, I'm not able to change the language

**Comment by khanhtrinh2308** [comment]
I'm trying this solution and it's working on my code _( Laravel )_

1. Use package **flowbite-datepicker**
2. At file **app.js** 
`import Datepicker from "flowbite-datepicker/Datepicker";
import vi from "../../node_modules/flowbite-datepicker/js/i18n/locales/vi.js";

const datepickerEl = document.getElementById('datepickerId');
Datepicker.locales.vi = vi.vi;
new Datepicker(datepickerEl, {
    language: 'vi',
    format: 'dd/mm/yyyy'
});

**Comment by khanhtrinh2308** [comment]
I'm trying this solution and it's working on my code _( Laravel )_

1. Use package **flowbite-datepicker**
2. At file **app.js**

```
import Datepicker from "flowbite-datepicker/Datepicker";
import vi from "../../node_modules/flowbite-datepicker/js/i18n/locales/vi.js";
const datepickerEl = document.getElementById('datepickerId');
Datepicker.locales.vi = vi.vi;
new Datepicker(datepickerEl, {
   language: 'vi',
   format: 'dd/mm/yyyy'
});
```

**Comment by zoltanszogyenyi** [comment]
Until we provide docs on this, please do:

1. Install the flowbite-datepicker plugin
2. Configure the languages via this guide: https://mymth.github.io/vanillajs-datepicker/#/i18n

Cheers,
Zoltan

**Comment by emmaLP** [comment]
Any update on this at all?

Use the CDN due to limitations with the hosting that it can only be a single HTML file and we pass the locale in as a query parameter so need the ability to set the language on page load.

Tried to follow the [docs](https://github.com/themesberg/flowbite-datepicker/blob/master/docs/i18n.md#for-browser) for CDN locale setting but all that does is install the datepicker by vanillajs

If you load the locales you want to support from vanillajs like the doc says, you end up with the vanillajs
![image](https://github.com/themesberg/flowbite/assets/10513197/b8903955-1668-40e1-9f77-3f2c72dbb955)
You can see the flowbite datepicker pop up and some really badly formatted vanillajs date picker.

**Comment by FitreeCodeConnext** [comment]
How to Change To th locale I tried all your methods. I did it in Laravel 10.

**Comment by zerossB** [comment]
> Until we provide docs on this, please do:
> 
>     1. Install the flowbite-datepicker plugin
> 
>     2. Configure the languages via this guide: https://mymth.github.io/vanillajs-datepicker/#/i18n
> 
> 
> Cheers, Zoltan

I'm trying to do as you indicated here, but it's not having any effect. Can you post a working example code so we can understand how it would work?

**Comment by wootitwebsolutions** [comment]
Here is one approach that can work for a site with different languages

In my blade file

```php
<input id="default-datepicker"  type="text" class="bg-gray-50 border border-gray-300 text-gray-900 rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5" placeholder="{{ __('Select your birthday') }}">
```
I installed the component via NPM
In my app.js

```js
import '../../node_modules/flowbite';
import Datepicker from '../../node_modules/flowbite-datepicker/js/datepicker';

import nl from '../../node_modules/flowbite-datepicker/js/i18n/locales/nl.js';
import fr from '../../node_modules/flowbite-datepicker/js/i18n/locales/fr.js';

var locale = document.documentElement.lang;

const datepickerEl = document.getElementById('default-datepicker');

const localeConfig = {
    en: { language: 'en', format: 'mm/dd/yyyy' },
    fr: { language: 'fr', format: 'dd/mm/yyyy', locale: fr.fr },
    nl: { language: 'nl', format: 'dd/mm/yyyy', locale: nl.nl }
};

if (localeConfig[locale]) {
    if (localeConfig[locale].locale) {
        Datepicker.locales[locale] = localeConfig[locale].locale;
    }
    new Datepicker(datepickerEl, {
        language: localeConfig[locale].language,
        format: localeConfig[locale].format,
        orientation: 'bottom',
        autohide: true
    });
}


```

**Comment by i3or1s** [comment]
None of the answers worked for me, and neither did the documents. However, I found a solution that might help someone, too. I lost too much time trying to figure it out. One thing I found in code is how datepicker is instantiated ```FlowbiteDatepicker```
```js
Datepicker.prototype.init = function () {
        if (this._datepickerEl && !this._initialized) {
            if (this._options.rangePicker) {
                this._datepickerInstance = new FlowbiteDateRangePicker(this._datepickerEl, this._getDatepickerOptions(this._options));
            }
            else {
                this._datepickerInstance = new FlowbiteDatepicker(this._datepickerEl, this._getDatepickerOptions(this._options));
            }
            this._initialized = true;
        }
    };
```
This was the turning point since I figured it uses ```FlowbiteDatepicker``` instead of ```Datepicker```, and all the solutions mention ```Datepicker```. So the solution was simple for me I just set the locale on ```FlowbiteDatepicker```

For those who are looking for the entire code (with just in case part)
```js
import 'flowbite';
// import Datepicker from 'flowbite-datepicker/Datepicker';
import sr from './../node_modules/flowbite-datepicker/js/i18n/locales/sr';
// Datepicker.locales.sr = sr.sr;
FlowbiteDatepicker.locales.sr = sr.sr;
```

One more detail is that HTML should also be configured
```html
 <input type="text"
            datepicker
            datepicker-language="sr"
            datepicker-format="dd.mm.yyyy"
>
```

**Comment by gritvald** [comment]
I've developed the following solution. It's a bit 'hackish,' but it works for me and doesn't require NPM installation. It handles the `Datepicker` and `DateRangePicker` components:

```javascript
window.addEventListener("load", () => {
    setTimeout(() => {
        let locales = {
            pl: {
                days: ["Niedziela", "Poniedziałek", "Wtorek", "Środa", "Czwartek", "Piątek", "Sobota"],
                daysShort: ["Niedz.", "Pon.", "Wt.", "Śr.", "Czw.", "Piąt.", "Sob."],
                daysMin: ["Ndz.", "Pn.", "Wt.", "Śr.", "Czw.", "Pt.", "Sob."],
                months: ["Styczeń", "Luty", "Marzec", "Kwiecień", "Maj", "Czerwiec", "Lipiec", "Sierpień", "Wrzesień", "Październik", "Listopad", "Grudzień"],
                monthsShort: ["Sty.", "Lut.", "Mar.", "Kwi.", "Maj", "Cze.", "Lip.", "Sie.", "Wrz.", "Paź.", "Lis.", "Gru."],
                today: "Dzisiaj",
                weekStart: 1,
                clear: "Wyczyść",
                format: "dd.mm.yyyy"
            }
        };
        let flowbitePickers = Object.values(FlowbiteInstances.getInstances("Datepicker")).map((instance) => {
            return instance.getDatepickerInstance();
        });
        for (const flowbitePicker of flowbitePickers) {
            for (const picker of flowbitePicker.datepickers || [flowbitePicker]) {
                Object.assign(picker.constructor.locales, locales);
                picker.setOptions({ language: "pl" });
            }
        }
    }, 100);
});
```

The hack is based on the line `const locales = datepicker.constructor.locales;` in the [`processOptions`](https://github.com/themesberg/flowbite-datepicker/blob/v1.3.0/js/options/processOptions.js#L40) function.

**Comment by leodip** [comment]
Sharing what I'm using in my application.

```jsx
import { useRef, useEffect } from 'react';
import PropTypes from 'prop-types';
import Datepicker from "flowbite-datepicker/Datepicker";

import pt from '../../node_modules/flowbite-datepicker/js/i18n/locales/pt.js';
import fr from '../../node_modules/flowbite-datepicker/js/i18n/locales/fr.js';

const LOCALES = {
    pt,
    fr
};

const FlowbiteDatepicker = ({
    id,
    placeholder = "Select a date",
    language = "en",
    onChange,
    className = "",
    ...props
}) => {
    const datepickerRef = useRef(null);
    const eventListenerRef = useRef(null);

    useEffect(() => {
        // cleanup previous instance and event listener
        const cleanup = () => {
            const element = document.getElementById(id);
            if (eventListenerRef.current && element) {
                element.removeEventListener('changeDate', eventListenerRef.current);
                eventListenerRef.current = null;
            }
            if (datepickerRef.current) {
                datepickerRef.current.destroy();
                datepickerRef.current = null;
            }
        };

        cleanup();

        const element = document.getElementById(id);
        if (!element) {
            return;
        }

        try {
            const today = new Date();
            const oneYearAgo = new Date(today);
            oneYearAgo.setFullYear(today.getFullYear() - 1);

            const oneYearAhead = new Date(today);
            oneYearAhead.setFullYear(today.getFullYear() + 1);

            // set your options here
            const instance = new Datepicker(element, {
                autohide: true,
                minDate: oneYearAgo,
                maxDate: oneYearAhead,
            });

            // apply localization if language is not English and locale exists
            if (language !== 'en' && LOCALES[language]) {
                Object.assign(instance.constructor.locales, LOCALES[language]);
                instance.setOptions({ language });
            }

            datepickerRef.current = instance;

            // store event listener reference for cleanup
            if (onChange) {
                const handleChange = (e) => {
                    onChange(e.detail.date);
                };
                eventListenerRef.current = handleChange;
                element.addEventListener('changeDate', handleChange);
            }
        } catch (error) {
            console.error('Error initializing datepicker:', error);
        }

        return () => {
            cleanup();
        };
    }, [id, language, onChange]);

    const defaultClassName = "bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500";

    return (
        <div className="relative max-w-sm">
            <div className="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
                <svg
                    className="w-4 h-4 text-gray-500 dark:text-gray-400"
                    aria-hidden="true"
                    xmlns="http://www.w3.org/2000/svg"
                    fill="currentColor"
                    viewBox="0 0 20 20"
                >
                    <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z" />
                </svg>
            </div>
            <input
                id={id}
                type="text"
                className={`${defaultClassName} ${className}`.trim()}
                placeholder={placeholder}
                {...props}
            />
        </div>
    );
};

FlowbiteDatepicker.propTypes = {
    id: PropTypes.string.isRequired,
    placeholder: PropTypes.string,
    language: PropTypes.oneOf(['en', 'pt', 'fr']),
    onChange: PropTypes.func,
    className: PropTypes.string,
};

export default FlowbiteDatepicker;
```

**Comment by eastsidekillas** [comment]
Hello, is the problem solved?

I'm trying to make a Datepicker on Angular 19, I tried to make my translation array this way.

```
const ru = {
  days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
  daysShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Суб"],
  daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
  months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
  monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
  today: "Сегодня",
  clear: "Очистить",
  format: "dd.mm.yyyy",
  weekStart: 1,
  monthsTitle: "Месяцы"
};


  ngAfterViewInit() {
    const input = this.elRef.nativeElement.querySelector('#datepicker-actions');
    if (input) {
      const options: DatepickerOptions = {
        format: 'dd.mm.yyyy',
        title: 'Выберите дату',
        language: 'ru',
        locales: { ru },
        buttons: true,
        autoSelectToday: 1
      };

      new Datepicker(input, options);
    }
  }
```



And it didn't work

**Comment by kafeltz** [comment]
Given that this issue has remained open since 2021, and it is now 2025 with i18n still not functioning, I propose that a volunteer from each country fork the project and translate the "en" variables into their native languages.

**Comment by leodip** [comment]
@kafeltz  Coincidência.... nós estudamos juntos na FURB 😅

**Comment by CODEheures** [comment]
@gritvald solution work! Thanks (others solutions don't work for me)
I adding attribute `datepicker-locale="fr"` on html  
(Example for symfony7 with asset mapper)

In app.js:
```javascript
import './styles/app.css';
import 'flowbite';
import 'flowbite-datepicker';
import fr from 'flowbite-datepicker/js/i18n/locales/fr.js';

window.addEventListener('load', () =>
{
	setTimeout(() =>
			   {
				   let flowbitePickers = Object.values(FlowbiteInstances.getInstances('Datepicker'))
											   .map((instance) =>
													{
														return instance.getDatepickerInstance();
													});

				   const languages = {
					   fr: fr
				   }

				   for (const flowbitePicker of flowbitePickers)
				   {
					   for (const picker of flowbitePicker.datepickers || [flowbitePicker])
					   {
						   const language = picker.element?.attributes['datepicker-language']?.value
						   if (language && language in languages)
						   {
							   Object.assign(picker.constructor.locales, languages[language]);
							   picker.setOptions({ language: language });
						   }
					   }
				   }
			   });
});
```

In html:
 ```html
 <input datepicker datepicker-format="dd/mm/yyyy"  datepicker-language="fr" ...>`
```

**Comment by CODEheures** [comment]
For symfony7 users with assets mapper I have a simple way:

Require language:
`php bin/console importmap:require flowbite-datepicker/js/i18n/locales/fr.js`

Create a class on assets/common for example:
```js
import fr from 'flowbite-datepicker/js/i18n/locales/fr.js';

class DatepickerI18n
{
	static languages = {
		fr: fr
	};

	static updateLanguage = (picker) => {
		const language = picker.element?.attributes['datepicker-language']?.value;
		if (language && language in DatepickerI18n.languages)
		{
			Object.assign(picker.constructor.locales, DatepickerI18n.languages[language]);
			picker.setOptions({ language: language });
		}
	}
}

export default DatepickerI18n;
```

Create a stimulus controller `assets/controllers/date_picker_controller.js`:

```js
import { Controller }   from '@hotwired/stimulus';
import { getComponent } from '@symfony/ux-live-component';
import DatepickerI18n   from '../common/flowbite/datepicker-i18n.js';

export default class extends Controller {

	static targets = ['input']

	async initialize() {
		this.component = await getComponent(this.element);
		const datepicker = this.inputTarget.datepicker;
		DatepickerI18n.updateLanguage(datepicker);

		this.inputTarget.addEventListener("changeDate", (event) => {
			this.inputTarget.dispatchEvent(new Event('change', { bubbles: true }))
		});
	}
}
```

Adding stimulus controller on html + adding datepicker-language="fr" (replace fr by the desire language) on input:
```html
<div {{ attributes.defaults(stimulus_controller('date_picker', {dateUpd: dateUpd})) }}>
    {{ this.dateUpd }}
    <div class="relative max-w-sm">
        <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
            <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
                <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
            </svg>
        </div>
        <input data-model="dateUpd" {{ stimulus_target('date_picker', 'input')}} datepicker datepicker-format="dd/mm/yyyy"  datepicker-language="fr" id="default-datepicker" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Choisir la date">
    </div>
</div>
```

Optionnaly create a Twig php component to manage date:
```php
namespace App\Twig\Components\Form;

use Symfony\UX\LiveComponent\Attribute\AsLiveComponent;
use Symfony\UX\LiveComponent\Attribute\LiveProp;
use Symfony\UX\LiveComponent\DefaultActionTrait;

#[AsLiveComponent]
final class Datepicker
{
	use DefaultActionTrait;

	#[LiveProp(writable: true)]
	public string $dateUpd;
}
```

**Comment by Andreibv** [comment]
> Hello, is the problem solved?
> 
> I'm trying to make a Datepicker on Angular 19, I tried to make my translation array this way.
> 
> ```
> const ru = {
>   days: ["Воскресенье", "Понедельник", "Вторник", "Среда", "Четверг", "Пятница", "Суббота"],
>   daysShort: ["Вск", "Пнд", "Втр", "Срд", "Чтв", "Птн", "Суб"],
>   daysMin: ["Вс", "Пн", "Вт", "Ср", "Чт", "Пт", "Сб"],
>   months: ["Январь", "Февраль", "Март", "Апрель", "Май", "Июнь", "Июль", "Август", "Сентябрь", "Октябрь", "Ноябрь", "Декабрь"],
>   monthsShort: ["Янв", "Фев", "Мар", "Апр", "Май", "Июн", "Июл", "Авг", "Сен", "Окт", "Ноя", "Дек"],
>   today: "Сегодня",
>   clear: "Очистить",
>   format: "dd.mm.yyyy",
>   weekStart: 1,
>   monthsTitle: "Месяцы"
> };
> 
> 
>   ngAfterViewInit() {
>     const input = this.elRef.nativeElement.querySelector('#datepicker-actions');
>     if (input) {
>       const options: DatepickerOptions = {
>         format: 'dd.mm.yyyy',
>         title: 'Выберите дату',
>         language: 'ru',
>         locales: { ru },
>         buttons: true,
>         autoSelectToday: 1
>       };
> 
>       new Datepicker(input, options);
>     }
>   }
> ```
> 
> And it didn't work

Did you find some solution ? Using angular and flowbite

**Comment by dust8** [comment]
flowbite里的datepicker官方不支持国际化, 但是flowbite引用的flowbite-datepicker里是支持的.
实现过程中踩了2个坑.
1. 因为使用的是flowbite里的datepicker, 而不是flowbite-datepicker, 所以需要找到flowbite-datepicker的实例才能设置. 而文档和issues里都没解释清楚, 导致设置不成功.
2. html中不用添加datepicker, date-rangepicker. 会造成被重置为默认语言en

下面给出一个完整的例子 

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <link href="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.css" rel="stylesheet" />
  <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"></script>
</head>
<body>
  <div class="relative max-w-sm">
    <div class="absolute inset-y-0 start-0 flex items-center ps-3.5 pointer-events-none">
      <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
        <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
      </svg>
    </div>
    <input id="default-datepicker" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date">
  </div>

  <div id="date-range-picker" class="flex items-center">
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
          </svg>
      </div>
      <input id="datepicker-range-start" name="start" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date start">
    </div>
    <span class="mx-4 text-gray-500">to</span>
    <div class="relative">
      <div class="absolute inset-y-0 start-0 flex items-center ps-3 pointer-events-none">
          <svg class="w-4 h-4 text-gray-500 dark:text-gray-400" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 20 20">
            <path d="M20 4a2 2 0 0 0-2-2h-2V1a1 1 0 0 0-2 0v1h-3V1a1 1 0 0 0-2 0v1H6V1a1 1 0 0 0-2 0v1H2a2 2 0 0 0-2 2v2h20V4ZM0 18a2 2 0 0 0 2 2h16a2 2 0 0 0 2-2V8H0v10Zm5-8h10a1 1 0 0 1 0 2H5a1 1 0 0 1 0-2Z"/>
          </svg>
      </div>
      <input id="datepicker-range-end" name="end" type="text" class="bg-gray-50 border border-gray-300 text-gray-900 text-sm rounded-lg focus:ring-blue-500 focus:border-blue-500 block w-full ps-10 p-2.5  dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" placeholder="Select date end">
  </div>
  </div>

  <script>
    // !!! html中不用添加datepicker, date-rangepicker. 会造成被重置为默认语言en
    // !!! There is no need to add datepicker, date-rangepicker in html. It will result in being reset to the default language en
    const locales ={'zh-CN': {
      days: ["星期日", "星期一", "星期二", "星期三", "星期四", "星期五", "星期六"],
      daysShort: ["周日", "周一", "周二", "周三", "周四", "周五", "周六"],
      daysMin: ["日", "一", "二", "三", "四", "五", "六"],
      months: ["一月", "二月", "三月", "四月", "五月", "六月", "七月", "八月", "九月", "十月", "十一月", "十二月"],
      monthsShort: ["1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月"],
      today: "今天",
      monthsTitle: "选择月份",
      clear: "清除",
      format: "yyyy-mm-dd",
      titleFormat: "y年mm月",
      weekStart: 1
    }};

    const setLanguage = (picker, locales)=>{
      // 因为使用的是flowbite里的Datepicker, 而不是flowbite-datepicker, 所以需要找到flowbite-datepicker的实例才能设置
      // Because the Datepicker in flowbite is used instead of flowbite-datepicker, an instance of flowbite-datepicker needs to be found to set it up
      const rangePicker = picker._options.rangePicker;
      const language = picker._options.language;

      if (!rangePicker){
          let vanillaInstance = picker.getDatepickerInstance();  
          Object.assign(vanillaInstance.constructor.locales, locales); 
          vanillaInstance.setOptions({language})
      }else{
          for(let vanillaInstance of picker._datepickerInstance.datepickers){
              Object.assign(vanillaInstance.constructor.locales, locales);  
              vanillaInstance.setOptions({language})
          }
      }
    }

    // Datepicker
    const $datepickerEl = document.getElementById('default-datepicker');
    const datepickerOptions = {
        rangePicker: false,
        language: 'zh-CN',  
    };
    const datepicker = new Datepicker($datepickerEl, datepickerOptions);
    setLanguage(datepicker, locales);


    // Date range picker
    const $daterangepickerEl = document.getElementById('date-range-picker');
    const daterangepickerOptions = {
        rangePicker: true,
        language: 'zh-CN',  
    };
    const daterangepicker = new Datepicker($daterangepickerEl, daterangepickerOptions);
    setLanguage(daterangepicker, locales);

  </script>
</body>
</html>
```

**Comment by tomazartack** [comment]
I got here from the documentation page, to find a solution. Since here are so many comments here, which solution is the one I should be using?
